export const SPANISH_MAP = {
  comida: ['Hamburger', 'Utensils', 'Pizza', 'Apple', 'Coffee', 'Sandwich', 'Cookie', 'Salad', 'Beef', 'Egg'],
  comer: ['Utensils', 'Hamburger', 'Pizza', 'Salad', 'Sandwich', 'Coffee'],
  cocina: ['Utensils', 'ChefHat', 'Flame', 'Coffee', 'Cookie', 'Sandwich'],
  bebida: ['Coffee', 'Wine', 'Beer', 'GlassWater', 'Milk', 'Cup'],
  cafe: ['Coffee', 'Cup', 'CupSoda'],
  dinero: ['Wallet', 'CreditCard', 'Banknote', 'Coins', 'PiggyBank', 'DollarSign', 'Receipt', 'Landmark'],
  plata: ['Wallet', 'CreditCard', 'Banknote', 'Coins', 'DollarSign'],
  pago: ['CreditCard', 'Wallet', 'Receipt', 'Banknote', 'QrCode'],
  banco: ['Landmark', 'Building', 'CreditCard', 'Banknote', 'Wallet'],
  ahorro: ['PiggyBank', 'Banknote', 'TrendingUp', 'BarChart2', 'Target', 'Percent', 'Wallet'],
  salud: ['Heart', 'Activity', 'Pill', 'Stethoscope', 'Bandage', 'Hospital', 'Thermometer', 'CrossIcon'],
  medico: ['Stethoscope', 'Hospital', 'Pill', 'Thermometer', 'Activity', 'Heart'],
  doctor: ['Stethoscope', 'Hospital', 'Pill', 'Thermometer', 'Activity'],
  farmacia: ['Pill', 'Cross', 'Thermometer', 'Stethoscope'],
  deporte: ['Dumbbell', 'Trophy', 'Medal', 'Bike', 'Footprints', 'Timer', 'Swords', 'Target'],
  ejercicio: ['Dumbbell', 'Footprints', 'Timer', 'Activity', 'Bike', 'Target'],
  gimnasio: ['Dumbbell', 'Activity', 'Target', 'Timer', 'Weight'],
  transporte: ['Car', 'Bus', 'Train', 'Bike', 'Plane', 'Ship', 'Truck', 'Fuel'],
  auto: ['Car', 'Fuel', 'Truck', 'Bus'],
  carro: ['Car', 'Fuel', 'Truck', 'Bus'],
  viaje: ['Plane', 'Map', 'Compass', 'Backpack', 'MapPin', 'Globe', 'Luggage', 'Suitcase'],
  viajar: ['Plane', 'Map', 'Compass', 'Backpack', 'Globe', 'Luggage'],
  vacaciones: ['Plane', 'Luggage', 'Sun', 'Map', 'Globe', 'Umbrella'],
  casa: ['Home', 'Building', 'Sofa', 'Bed', 'Bath', 'Key', 'Lamp', 'DoorOpen'],
  hogar: ['Home', 'Sofa', 'Refrigerator', 'Plug', 'Lightbulb', 'Lamp', 'Bed'],
  trabajo: ['Briefcase', 'Laptop', 'Building2', 'HardHat', 'Wrench', 'Settings', 'Pen', 'Monitor'],
  oficina: ['Briefcase', 'Monitor', 'Laptop', 'Pen', 'Printer', 'Building2'],
  educacion: ['Book', 'GraduationCap', 'Pencil', 'School', 'Library', 'Brain', 'BookOpen', 'Backpack'],
  estudiar: ['Book', 'BookOpen', 'Pencil', 'Brain', 'GraduationCap', 'Library'],
  escuela: ['School', 'Book', 'Pencil', 'GraduationCap', 'Backpack', 'Library'],
  entretenimiento: ['Music', 'Tv', 'Gamepad2', 'Film', 'Ticket', 'PartyPopper', 'Headphones', 'Clapperboard'],
  musica: ['Music', 'Headphones', 'Mic', 'Radio', 'Guitar', 'Piano'],
  pelicula: ['Film', 'Tv', 'Clapperboard', 'Ticket', 'Video'],
  ropa: ['Shirt', 'ShoppingBag', 'Tag', 'Scissors', 'Watch', 'Gem', 'Package'],
  moda: ['Shirt', 'Gem', 'Watch', 'ShoppingBag', 'Tag', 'Scissors'],
  mascota: ['Dog', 'Cat', 'Bird', 'Fish', 'Rabbit', 'PawPrint', 'Bone'],
  perro: ['Dog', 'Bone', 'PawPrint'],
  gato: ['Cat', 'PawPrint'],
  tecnologia: ['Laptop', 'Smartphone', 'Monitor', 'Cpu', 'Wifi', 'BatteryCharging', 'Code'],
  compras: ['ShoppingCart', 'ShoppingBag', 'Tag', 'CreditCard', 'Store', 'Package'],
  regalo: ['Gift', 'PartyPopper', 'Cake', 'Sparkles', 'Star'],
  familia: ['Users', 'Baby', 'Heart', 'Home', 'Smile'],
  amigos: ['Users', 'Smile', 'Heart', 'MessageCircle', 'PartyPopper'],
  naturaleza: ['Leaf', 'Flower2', 'Sun', 'Cloud', 'Tree', 'Mountain', 'Bird'],
  sol: ['Sun', 'Cloud', 'Sunrise', 'Sunset'],
  lluvia: ['Cloud', 'CloudRain', 'Umbrella', 'Droplets'],
  negocio: ['Briefcase', 'BarChart2', 'TrendingUp', 'Building2', 'DollarSign', 'Target'],
  inversion: ['TrendingUp', 'BarChart2', 'DollarSign', 'PiggyBank', 'Percent', 'LineChart'],
  deuda: ['CreditCard', 'Banknote', 'Receipt', 'AlertCircle', 'Wallet'],
  impuesto: ['Receipt', 'FileText', 'Percent', 'Landmark', 'DollarSign'],
  seguro: ['Shield', 'ShieldCheck', 'Heart', 'Car', 'Home', 'Umbrella'],
  servicios: ['Zap', 'Droplets', 'Wifi', 'Phone', 'Flame', 'Plug'],
  agua: ['Droplets', 'GlassWater', 'Waves', 'CloudRain'],
  luz: ['Zap', 'Lightbulb', 'Flame', 'Sun', 'Plug'],
  celular: ['Smartphone', 'Phone', 'Wifi', 'MessageCircle', 'PhoneCall'],
  internet: ['Wifi', 'Globe', 'Signal', 'Laptop', 'Monitor'],
  cine: ['Film', 'Ticket', 'Clapperboard', 'Tv', 'Video'],
  libro: ['Book', 'BookOpen', 'Library', 'Bookmark', 'Pen'],
  arte: ['Palette', 'Brush', 'PenTool', 'Pen', 'Scissors', 'Camera'],
  foto: ['Camera', 'Image', 'Aperture', 'Focus'],
}
